import type { MetadataRoute } from 'next';

export const dynamic = 'force-static';

const baseUrl = 'https://www.whisperofthehouse.com';

// Keep one canonical path per indexable page.
// Historical pages intentionally omit lastModified when the real date is unknown.
const paths = [
  '/',
  '/guides',
  '/winter-burrow',
  '/routine-guide',
  '/retro-rewind',
  '/i-am-alone',
  '/collection',
  '/abnormal-points-collection',
  '/play-online',
  '/papas-wingeria',
  '/steal-brainrot',
  '/vikings-an-archers-journey',
  '/tree-house-maker',
  '/horseshoeing',
  '/panda-resort',
  '/puppet-master',
  '/blumgi-slime',
  '/grow-a-garden',
  '/guide/hozy',
  '/the-long-dark-episode-5',
  '/i-am-jesus-christ',
  '/all-will-fall',
  '/the-occultist',
  '/soulmask',
  '/crystalfall',
  '/sol-cesto',
  '/pokemon-champions',
  '/grime-2',
  '/road-to-vostok',
  '/mouse-pi-for-hire/collectibles-hub',
  '/pragmata',
  '/sintopia',
  '/airborne-empire',
  '/lucky-tower-ultimate',
  '/vampire-crawlers',
  '/holovillage-our-cozy-days',
  '/shapez-2',
  '/fracture-field',
  '/moomintroll',
  '/far-far-west/secret-missions',
  '/olden-era',
  '/gamble-with-your-friends',
  '/magical-princess/endings-guide',
  '/librarian',
  '/farever',
  '/everything-is-crab',
  '/the-spell-brigade',
  '/outbound',
  '/directive-8020',
  '/subnautica-2',
  '/oaken-tower',
  '/dwarf-eats-mountain',
  '/lego-batman',
  '/deep-rock-galactic',
  '/zero-parades',
  '/paralives',
  '/romestead',
  '/starminer',
  '/cheap-car-repair',
  '/mina-the-hollower',
  '/scale-the-depths',
  '/fatekeeper',
  '/realm-of-ink',
  '/house-flipper-remastered-collection',
  '/gothic-1-remake',
  '/solarpunk',
  '/voidling-bound',
  '/burglin-gnomes',
  '/fears-to-fathom-scratch-creek',
  '/spacecraft',
  '/tales-of-seikyu',
  '/33-immortals',
  '/the-adventures-of-elliot',
  '/steam-next-fest',
  '/bombanana',
  '/casualties-unknown',
  '/dust-front-rts',
  '/thank-you-for-your-application',
  '/best-cozy-management-crafting-games',
  '/best-games-with-multiple-endings',
  '/best-steam-indie-games-with-guides',
  '/new-steam-game-guides',
  '/timberborn',
  '/moldwasher',
  '/darktide',
  '/the-last-caretaker',
  '/deltarune',
  '/frostpunk-2-breach-of-trust',
  '/supermarket-chaos',
  '/the-binding-of-isaac-rebirth',
  '/master-healer-kale',
  '/esports-manager-2026',
  '/moonlight-peaks',
  '/granblue-relink-endless-ragnarok',
  '/forest-escape-last-train',
  '/backyard-baseball',
  '/ascend-to-zero',
  '/the-incident-at-galley-house',
  '/ore-factory-squad',
  '/happys-humble-burger-cult',
  '/zerospace',
  '/dragonsword-awakening',
  '/tears-of-metal',
  '/dirty-business',
  '/grim-dawn-fangs-of-asterkarn',
  '/game-dna',
  '/what-game-should-i-play',
  '/go-go-town',
  '/scrap-mechanic',
  '/sir-we-have-an-orc-problem',
  '/bills-must-be-paid',
  '/how-many-dudes',
  '/waterpark-simulator',
  '/quasimorph',
  '/idle-directive',
  '/idle-directive/first-prestige-best-augments',
  '/idle-directive/automation-machines-guide',
  '/idle-directive/layout-examples',
  '/idle-directive/achievements-guide',
  '/quasimorph/beginner-guide',
  '/quasimorph/contracts-guide',
  '/quasimorph/ship-upgrades',
  '/quasimorph/loot-priority',
  '/quasimorph/wounds-infection-medicine',
  '/quasimorph/start-realware-storyline',
  '/quasimorph/quasimorphosis-guide',

  '/waterpark-simulator/research-points',
  '/waterpark-simulator/increase-satisfaction',
  '/waterpark-simulator/make-money',
  '/waterpark-simulator/staff-guide',
  '/waterpark-simulator/museum-guide',
  '/waterpark-simulator/achievements-guide',
  '/waterpark-simulator/5-star-diamond-prestige-guide',
  '/waterpark-simulator/mafia-guide',
  '/waterpark-simulator/custom-slides-guide',

  '/how-many-dudes/goat-boss-guide',
  '/how-many-dudes/best-builds',
  '/how-many-dudes/round-100-guide',
  '/how-many-dudes/relic-combinations',
  '/how-many-dudes/tier-2-progression',
  '/how-many-dudes/achievements-guide',
  '/bills-must-be-paid/100-percent-walkthrough',
  '/bills-must-be-paid/achievements-guide',
  '/bills-must-be-paid/best-upgrades-skill-tree',
  '/bills-must-be-paid/bills-loans-bankruptcy',
  '/bills-must-be-paid/prestige-rings-bracelets',
  '/sir-we-have-an-orc-problem/best-turrets-builds',
  '/sir-we-have-an-orc-problem/best-upgrades-farming',
  '/sir-we-have-an-orc-problem/level-3-2-guide',
  '/sir-we-have-an-orc-problem/level-6-1-6-2-guide',
  '/scrap-mechanic/first-grow-lab-walkthrough',
  '/scrap-mechanic/warehouse-key',
  '/scrap-mechanic/warehouse-walkthrough',
  '/scrap-mechanic/hubert-watchtower-small-tank',
  '/scrap-mechanic/mining-guide',
  '/scrap-mechanic/achievements',
  '/scrap-mechanic/ore-processing-guide',
  '/go-go-town/agent-peanut-safe-code',
  '/go-go-town/automation-not-working',
  '/go-go-town/progression-stuck',
  '/grim-dawn-fangs-of-asterkarn/wereraven-leveling-build',
  '/grim-dawn-fangs-of-asterkarn/the-asterkarn-incident-walkthrough',
  '/grim-dawn-fangs-of-asterkarn/ritual-of-cleansing-walkthrough',
  '/grim-dawn-fangs-of-asterkarn/soul-echoes-awaken-epic-items',
  '/dirty-business/orders-delivery-guide',
  '/dirty-business/workers-not-working',
  '/dirty-business/leveling-reputation-unlocks',
  '/dirty-business/how-to-make-lsd',
  '/dirty-business/achievements-guide',
  '/tears-of-metal/beginner-guide',
  '/tears-of-metal/best-builds',
  '/tears-of-metal/village-upgrades',
  '/tears-of-metal/co-op-guide',
  '/tears-of-metal/boss-guide',
  '/tears-of-metal/characters-companion-unlocks',
  '/dragonsword-awakening/walkthrough',
  '/dragonsword-awakening/ending-final-boss',
  '/dragonsword-awakening/beginner-guide',
  '/dragonsword-awakening/gear-karma-guide',
  '/dragonsword-awakening/best-team-comps',
  '/zerospace/beginner-guide',
  '/zerospace/galactic-war-beginner-guide',
  '/zerospace/campaign-walkthrough-choices',
  '/zerospace/mission-3-arcadia-walkthrough',
  '/happys-humble-burger-cult/beginner-guide',
  '/happys-humble-burger-cult/quota-overtime-closeout-guide',
  '/happys-humble-burger-cult/orders-kitchen-guide',
  '/ore-factory-squad/beginner-guide',
  '/ore-factory-squad/how-to-sell-products',
  '/ore-factory-squad/complete-contracts-pallet-packer',
  '/ore-factory-squad/mining-lift-guide',
  '/ore-factory-squad/find-limestone-make-cement',
  '/ore-factory-squad/remaining-resources-switch-property',
  '/ore-factory-squad/dynamite-worth-it',
  '/ore-factory-squad/smelt-copper-iron-ingots',
  '/the-incident-at-galley-house/hints',
  '/the-incident-at-galley-house/person-12-person-k',
  '/the-incident-at-galley-house/ending-explained',
  '/the-incident-at-galley-house/achievements-guide',
  '/the-incident-at-galley-house/all-scene-codes',
  '/ascend-to-zero/how-to-unlock-stage-2-desert',
  '/ascend-to-zero/best-builds',
  '/ascend-to-zero/achievements-guide',
  '/forest-escape-last-train/unlock-all-players',
  '/forest-escape-last-train/beginner-guide',
  '/forest-escape-last-train/best-players-team-lineup',
  '/forest-escape-last-train/achievements-guide',
  '/forest-escape-last-train/locations-puzzle-guide',
  '/forest-escape-last-train/warden-boss-guide',
  '/granblue-relink-endless-ragnarok/how-to-start',
  '/granblue-relink-endless-ragnarok/conflux-guide',
  '/granblue-relink-endless-ragnarok/fatebreaker-chaos-progression',
  '/granblue-relink-endless-ragnarok/best-ai-team-builds',
  '/granblue-relink-endless-ragnarok/new-characters-unlock-guide',
  '/moonlight-peaks/beginner-guide',
  '/moonlight-peaks/misty-shores-mines-copper-guide',
  '/moonlight-peaks/early-resources-tool-upgrades-guide',
  '/moonlight-peaks/feature-unlocks-guide',
  '/moonlight-peaks/barn-animals-guide',
  '/esports-manager-2026/beginner-guide',
  '/esports-manager-2026/training-tactics-guide',
  '/esports-manager-2026/achievements-guide',
  '/esports-manager-2026/scouting-contracts-guide',
  '/esports-manager-2026/sponsors-budget-guide',
  '/master-healer-kale/achievements-guide',
  '/master-healer-kale/best-skills-skill-tree',
  '/master-healer-kale/nightmare-mode-endgame',
  '/the-binding-of-isaac-rebirth/dlc-buying-guide',
  '/the-binding-of-isaac-rebirth/beginner-guide',
  '/the-binding-of-isaac-rebirth/unlock-order',
  '/the-binding-of-isaac-rebirth/tainted-characters-unlock-guide',
  '/the-binding-of-isaac-rebirth/best-beginner-characters',
  '/supermarket-chaos/achievements-guide',
  '/supermarket-chaos/beginner-guide',
  '/supermarket-chaos/best-upgrades-skills',
  '/supermarket-chaos/section-map-item-locations',
  '/frostpunk-2-breach-of-trust/walkthrough',
  '/frostpunk-2-breach-of-trust/aurora-negotiation-fishery-hub-guide',
  '/frostpunk-2-breach-of-trust/conquer-aurora-war-route-guide',
  '/frostpunk-2-breach-of-trust/tremor-evacuation-guide',
  '/deltarune/chapter-5-final-boss-guide',
  '/deltarune/chapter-5-foxes-secret-egg',
  '/deltarune/chapter-5-secret-boss-guide',
  '/deltarune/chapter-5-secret-boss-pink-coins',
  '/deltarune/chapter-5-weird-route',
  '/the-last-caretaker/new-horizons-guide',
  '/the-last-caretaker/project-eden-guide',
  '/the-last-caretaker/oil-whale-guide',
  '/the-last-caretaker/research-outpost-theta-9-guide',
  '/the-last-caretaker/power-fuel-wall-outlets',
  '/darktide/best-skitarii-builds',
  '/darktide/skitarii-servo-skull',
  '/darktide/skitarii-weapons',
  '/moldwasher/achievements-guide',
  '/moldwasher/walkthrough',
  '/moldwasher/hidden-objects-collectibles',
  '/timberborn/beginner-guide',
  '/timberborn/first-drought-guide',
  '/timberborn/dam-levee-floodgate-guide',
  '/timberborn/badwater-badtide-guide',
  '/timberborn/irrigation-reservoir-guide',
  '/timberborn/automation-guide',
  '/thank-you-for-your-application/achievements-guide',
  '/thank-you-for-your-application/endings-guide',
  '/thank-you-for-your-application/final-evaluation-job-hopping-answers',
  '/thank-you-for-your-application/beginner-guide',
  '/thank-you-for-your-application/resume-rules-thanks-letter-guide',
  '/the-adventures-of-elliot/achievements-guide',
  '/the-adventures-of-elliot/beginner-guide',
  '/the-adventures-of-elliot/cat-locations',
  '/the-adventures-of-elliot/walkthrough',
  '/the-adventures-of-elliot/shards-of-life-locations',
  '/the-adventures-of-elliot/manuscript-locations',
  '/33-immortals/beginner-progression-guide',
  '/33-immortals/weapons-unlock-upgrades-guide',
  '/33-immortals/relics-paths-wishing-guide',
  '/33-immortals/bosses-guide',
  '/33-immortals/achievements-guide',
  '/tales-of-seikyu/beginner-guide',
  '/tales-of-seikyu/fox-ruins-guide',
  '/tales-of-seikyu/yokai-forms-guide',
  '/tales-of-seikyu/request-board-guide',
  '/tales-of-seikyu/achievements-guide',
  '/tales-of-seikyu/romance-gifts-marriage-guide',
  '/spacecraft/beginner-guide',
  '/spacecraft/base-building-automation',
  '/spacecraft/scanalyzer-alpha-ftl-engine',
  '/spacecraft/resources-locations',
  '/spacecraft/ship-upgrades-cargo-inventory',
  '/spacecraft/noviciate-corporation-unlock',
  '/spacecraft/permits-knowledge-unlock',
  '/fears-to-fathom-scratch-creek/walkthrough',
  '/fears-to-fathom-scratch-creek/ending-guide',
  '/fears-to-fathom-scratch-creek/achievements-guide',
  '/burglin-gnomes/beginner-guide',
  '/burglin-gnomes/tasks-guide',
  '/burglin-gnomes/survival-enemies-guide',
  '/burglin-gnomes/co-op-guide',
  '/burglin-gnomes/materials-upgrades-guide',
  '/voidling-bound/all-collectibles',
  '/voidling-bound/beginner-guide',
  '/voidling-bound/evolution-breeding-splicing-guide',
  '/voidling-bound/golden-egg-locations',
  '/voidling-bound/mutagen-research-points-farm',
  '/voidling-bound/quackies-locations',
  '/voidling-bound/breeding-guide',
  '/solarpunk/beginners-guide',
  '/solarpunk/energy-system-guide',
  '/solarpunk/airship-guide',
  '/solarpunk/farming-guide',
  '/solarpunk/research-progression-guide',
  '/solarpunk/animals-guide',
  '/gothic-1-remake/beginner-guide',
  '/gothic-1-remake/perfect-start',
  '/gothic-1-remake/early-ore-weapons-armor',
  '/gothic-1-remake/best-faction',
  '/gothic-1-remake/old-camp-walkthrough',
  '/gothic-1-remake/old-mine-diegos-list',
  '/gothic-1-remake/new-camp-walkthrough',
  '/gothic-1-remake/swamp-camp-walkthrough',
  '/gothic-1-remake/skills-trainers',
  '/gothic-1-remake/lockpicking-guide',
  '/house-flipper-remastered-collection/beginner-guide',
  '/house-flipper-remastered-collection/first-jobs-walkthrough',
  '/house-flipper-remastered-collection/money-guide',
  '/house-flipper-remastered-collection/achievements-guide',
  '/house-flipper-remastered-collection/dlc-content-guide',
  '/realm-of-ink/beginner-guide',
  '/realm-of-ink/best-builds',
  '/realm-of-ink/endless-rupture-guide',
  '/realm-of-ink/final-boss-true-ending',
  '/realm-of-ink/ink-gems-curios-guide',
  '/realm-of-ink/oread-guide',
  '/fatekeeper/beginner-guide',
  '/fatekeeper/best-build',
  '/fatekeeper/boss-guide',
  '/fatekeeper/best-weapons',
  '/fatekeeper/best-spells',
  '/scale-the-depths/huatulco-100-percent-guide',
  '/scale-the-depths/loch-ness-100-percent-guide',
  '/scale-the-depths/outer-banks-100-percent-guide',
  '/scale-the-depths/point-nemo-100-percent-guide',
  '/scale-the-depths/all-collectibles-secrets',
  '/scale-the-depths/achievement-guide',
  '/scale-the-depths/artifacts-guide',
  '/mina-the-hollower/where-to-go-first',
  '/mina-the-hollower/how-to-get-map',
  '/mina-the-hollower/bones-farming',
  '/mina-the-hollower/best-starting-weapon',
  '/mina-the-hollower/fast-travel',
  '/mina-the-hollower/best-early-trinkets',
  '/mina-the-hollower/all-trinkets-guide',
  '/cheap-car-repair/daddys-little-girl-mission',
  '/cheap-car-repair/controls-drop-items-save-tools',
  '/cheap-car-repair/how-to-make-money',
  '/cheap-car-repair/story-missions-walkthrough',
  '/cheap-car-repair/cars-parts-guide',
  '/starminer/beginner-first-hour',
  '/starminer/controls-dampeners-ship-spinning',
  '/starminer/early-research-progression',
  '/starminer/how-to-mine-scanner-laser',
  '/starminer/money-selling-resources',
  '/starminer/power-heat-low-energy',
  '/romestead/dungeon-traps-death-recovery',
  '/romestead/farmstead-workers-food-logistics',
  '/romestead/first-day-base-building',
  '/romestead/giant-owl-guardian-of-minerva',
  '/romestead/gods-offerings-boss-progression',
  '/romestead/base-layout-guide',
  '/romestead/raid-defense-guide',
  '/paralives/paramaker-stats-vibes-personality',
  '/paralives/best-early-game-skills-talents-careers',
  '/paralives/job-performance-not-improving',
  '/paralives/level-skills-faster',
  '/paralives/best-mods-steam-workshop-install-guide',
  '/paralives/money-cheats-paradimes',
  '/paralives/try-for-baby-not-showing',
  '/zero-parades/best-build',
  '/zero-parades/conditioning',
  '/zero-parades/disco-elysium-guide',
  '/zero-parades/stress-exertion',
  '/zero-parades/early-game',
  '/deep-rock-galactic/beginner-guide',
  '/deep-rock-galactic/best-class',
  '/deep-rock-galactic/cooper-guide',
  '/deep-rock-galactic/rogue-core-vs-drg',
  '/deep-rock-galactic/solo-guide',
  '/deep-rock-galactic/upgrades-explained',
  '/lego-batman/carmine-falcone',
  '/lego-batman/red-bricks',
  '/lego-batman/batgirl-unlock',
  '/lego-batman/firefly-boss',
  '/lego-batman/poison-ivy-boss',
  '/lego-batman/bane-boss',
  '/lego-batman/escaped-zoo-animals',
  '/lego-batman/mr-freeze-boss',
  '/lego-batman/new-beginnings-docks-collectibles',
  '/lego-batman/radio-towers',
  '/lego-batman/absolute-batman-suit',
  '/lego-batman/all-subwayne-tunnel-locations',
  '/lego-batman/how-to-farm-studs-fast',
  '/dwarf-eats-mountain/build-order',
  '/dwarf-eats-mountain/prestige-ascension-guide',
  '/dwarf-eats-mountain/runners-guide',
  '/dwarf-eats-mountain/artifacts-mithril-guide',
  '/dwarf-eats-mountain/best-builds',
  '/dwarf-eats-mountain/endgame-guide',
  '/subnautica-2/biomods-guide',
  '/subnautica-2/co-op-guide',
  '/subnautica-2/collector-leviathan',
  '/subnautica-2/digestion-adaptation',
  '/subnautica-2/early-resources',
  '/subnautica-2/first-base-setup',
  '/subnautica-2/fully-functional-fabricator',
  '/subnautica-2/navigation-guide',
  '/subnautica-2/oxygen-air-tank-rebreather',
  '/subnautica-2/sonic-resonator-guide',
  '/subnautica-2/tadpole-submarine',
  '/subnautica-2/welcome-center-habitat-builder',
  '/subnautica-2/what-to-do-first',
  '/oaken-tower/poison-build',
  '/oaken-tower/10-wins-guide',
  '/oaken-tower/level-vs-reroll',
  '/oaken-tower/3-star-items',
  '/oaken-tower/perk-unlock-guide',
  '/oaken-tower/bleed-build',
  '/oaken-tower/burn-build',
  '/oaken-tower/frosty-build',
  '/directive-8020/all-endings',
  '/directive-8020/all-monster-scenes-alien-duplicates',
  '/directive-8020/all-secrets-simms-recordings-o-death',
  '/directive-8020/character-survival-guide',
  '/directive-8020/choices-consequences',
  '/outbound/leave-first-biome',
  '/outbound/energy-guide',
  '/outbound/early-resources',
  '/outbound/blueprints-workstations-upgrades',
  '/outbound/storage-backpack-guide',
  '/the-spell-brigade/achievements-guide',
  '/the-spell-brigade/best-builds',
  '/the-spell-brigade/best-spells-elements',
  '/the-spell-brigade/gold-farm',
  '/the-spell-brigade/solo-guide',
  '/the-spell-brigade/wizard-unlocks',
  '/the-spell-brigade/trial-covenants-masteries-prestige',
  '/everything-is-crab/achievements-challenges-guide',
  '/everything-is-crab/best-builds',
  '/everything-is-crab/boss-guide',
  '/everything-is-crab/progression-guide',
  '/everything-is-crab/selective-pressure-guide',
  '/farever/beginner-guide',
  '/farever/classes-guide',
  '/farever/codeex-leveling-guide',
  '/farever/mount-guide',
  '/farever/weapon-skills-guide',
  '/librarian/achievements',
  '/librarian/best-abilities',
  '/librarian/book-sorting',
  '/librarian/key-locations',
  '/magical-princess/forbidden-research-guide',
  '/magical-princess/two-queens-ending-guide',
  '/magical-princess/true-ending-heir-of-the-stargazer',
  '/magical-princess/golden-ending-guide',
  '/magical-princess/career-endings-requirements',
  '/gamble-with-your-friends/achievements',
  '/gamble-with-your-friends/beginner-guide',
  '/gamble-with-your-friends/best-games',
  '/gamble-with-your-friends/best-item-combos',
  '/gamble-with-your-friends/craps-cheese-guide',
  '/gamble-with-your-friends/tickets-items-body-parts',
  '/gamble-with-your-friends/all-endings-guide',
  '/gamble-with-your-friends/bugged-achievements',
  '/gamble-with-your-friends/quota-guide',
  '/gamble-with-your-friends/save-scum-guide',
  '/olden-era/best-buildings-first',
  '/olden-era/cant-unlock-subclass',
  '/olden-era/chronomancer-vs-soulweaver',
  '/olden-era/focus-points',
  '/olden-era/force-subclass',
  '/olden-era/how-to-unlock-subclasses',
  '/olden-era/law-points-astrology-points',
  '/olden-era/necropolis-common-mistakes',
  '/olden-era/necropolis-guide',
  '/olden-era/necropolis-skeletal-archers',
  '/olden-era/necropolis-week-1-build-order',
  '/olden-era/subclass-guide',
  '/far-far-west/area-41-symbol-order',
  '/far-far-west/cactus-day-joker-locations',
  '/far-far-west/canyon-secret-medallion-locations',
  '/far-far-west/ghost-bell-shard-locations',
  '/far-far-west/snowman-parts-locations',
  '/far-far-west/woodlands-mushroom-sequence',
  '/far-far-west/all-secret-jokers',
  '/moomintroll/achievements-guide',
  '/moomintroll/ending-explained',
  '/moomintroll/great-winter-bonfire',
  '/moomintroll/little-my-snowball-fight',
  '/moomintroll/side-quests',
  '/moomintroll/tool-upgrades',
  '/moomintroll/vase-piece-locations',
  '/fracture-field/achievements-guide',
  '/fracture-field/beginner-walkthrough',
  '/fracture-field/prestige-guide',
  '/fracture-field/progression-guide',
  '/shapez-2/mam-guide',
  '/shapez-2/manufacture-mode-guide',
  '/shapez-2/trade-station-guide',
  '/shapez-2/wires-belt-filter-guide',
  '/shapez-2/space-belts-trains-guide',
  '/holovillage-our-cozy-days/beginner-guide',
  '/holovillage-our-cozy-days/early-combat-guide',
  '/holovillage-our-cozy-days/fishing-guide',
  '/holovillage-our-cozy-days/how-to-invite-villagers',
  '/holovillage-our-cozy-days/shop-money-guide',
  '/vampire-crawlers/all-characters-unlock-guide',
  '/vampire-crawlers/best-characters-for-beginners',
  '/vampire-crawlers/secret-characters-how-to-unlock',
  '/vampire-crawlers/best-early-upgrades',
  '/vampire-crawlers/combo-guide',
  '/vampire-crawlers/early-evolutions',
  '/airborne-empire/jet-engine-guide',
  '/airborne-empire/kingsfell-guide',
  '/airborne-empire/pirate-queen-guide',
  '/airborne-empire/tilt-lift-balance-guide',
  '/sintopia/best-hell-layout-guide',
  '/sintopia/hearos-guide',
  '/sintopia/overworld-guide',
  '/sintopia/saints-guide',
  '/mouse-pi-for-hire/baseball-card-locations',
  '/mouse-pi-for-hire/buy-back-guide',
  '/mouse-pi-for-hire/missable-side-job-rewards',
  '/mouse-pi-for-hire/missables-guide',
  '/mouse-pi-for-hire/mouseberg-herald-comic-locations',
  '/mouse-pi-for-hire/weapon-schematics-secret-figurines-guide',
  '/road-to-vostok/area-05-guide',
  '/road-to-vostok/generalist-and-doctor-locations',
  '/road-to-vostok/permadeath-save-and-stash-guide',
  '/road-to-vostok/all-shelter-locations',
  '/pokemon-champions/how-to-beat-tailwind-pokemon-champions-doubles',
  '/pokemon-champions/how-to-beat-trick-room-pokemon-champions-doubles',
  '/pokemon-champions/how-to-counter-incineroar-pokemon-champions-doubles',
  '/pokemon-champions/how-to-deal-with-sneasler-pokemon-champions-doubles',
  '/grime-2/blade-mammoth-boss-guide',
  '/grime-2/kankan-guide',
  '/grime-2/vs-grime-1-differences',
  '/grime-2/best-early-weapons',
  '/sol-cesto/all-characters-unlock-guide',
  '/sol-cesto/flute-guide',
  '/sol-cesto/how-to-unlock-huntress',
  '/sol-cesto/how-to-unlock-lizard',
  '/crystalfall/beginner-guide',
  '/crystalfall/crafting-sockets-gem-fusion-guide',
  '/crystalfall/fireball-build-guide',
  '/crystalfall/inventory-stash-guide',
  '/soulmask/airship-guide',
  '/soulmask/cross-map-transfer-guide',
  '/soulmask/shifting-sands-beginner-guide',
  '/soulmask/tribesmen-guide',
  '/the-occultist/all-altar-locations',
  '/the-occultist/all-medallion-locations',
  '/the-occultist/codex-lumina-fragments',
  '/the-occultist/clock-room-sundial-puzzle-solution',
  '/the-occultist/greenhouse-statue-puzzle-solution',
  '/the-occultist/mausoleum-door-lion-key-puzzle-solution',
  '/the-occultist/planetarium-star-moon-puzzle-solution',
  '/the-long-dark-episode-5/search-party-achievement',
  '/the-long-dark-episode-5/what-to-do-after-the-autopsy',
  '/the-long-dark-episode-5/where-to-go-after-terry',
  '/the-long-dark-episode-5/how-to-get-to-desperation-bay',
  '/all-will-fall/oil-rig-guide',
  '/all-will-fall/tanker-truck-guide',
  '/all-will-fall/tornado-race-guide',
  '/all-will-fall/collapse-troubleshooting',
  '/i-am-jesus-christ/apostles-locations',
  '/i-am-jesus-christ/miracles-list',
  '/i-am-jesus-christ/walkthrough',
  '/i-am-jesus-christ/who-should-play',
  '/the-long-dark-episode-5/episode-5-ending-explained',
  '/the-long-dark-episode-5/episode-5-missing-people-locations',
  '/the-long-dark-episode-5/episode-5-walkthrough',
  '/the-long-dark-episode-5/whats-in-astrids-hardcase-explained',
  '/guides/hozy/cafe-layout-tips',
  '/guides/hozy/dreams-explained',
  '/guides/hozy/hardest-levels-ranked',
  '/guides/hozy/penthouse-layout-guide',
  '/retro-rewind/is-the-black-market-worth-it',
  '/retro-rewind/when-to-replace-damaged-tape',
  '/retro-rewind/custom-videos',
  '/retro-rewind/community',
  '/guides/beginner-guide',
  '/guides/game-progression-guide',
  '/guides/top-tips-and-tricks',
  '/guides/hidden-secrets',
  '/guides/organize-and-uncover-secrets',
  '/winter-burrow/winter-burrow-early-survival-guide',
  '/winter-burrow/winter-burrow-owl-chase-part2-guide',
  '/winter-burrow/winter-burrow-gnawtusk-rescue-chapter-guide',
  '/winter-burrow/winter-burrow-bufo-request-part4-guide',
  '/winter-burrow/winter-burrow-finding-poliwog-walkthrough',
  '/i-am-alone/how-to-get-all-endings-yes-im-alone',
  '/routine-guide/chapter-1-birth-stealth-walkthrough',
  '/routine-guide/chapter-2-incision-stealth-walkthrough',
  '/routine-guide/chapter-3-re-create-stealth-walkthrough',
  '/routine-guide/chapter-4-adrift-stealth-walkthrough',
  '/routine-guide/chapter-5-endure-stealth-walkthrough',
  '/routine-guide/chapter-6-legacy-stealth-walkthrough',

  '/big-walk',
  '/big-walk/beginner-guide',
  '/big-walk/tutorial-walkthrough',
  '/big-walk/how-to-unlock-map',
  '/big-walk/green-tower-walkthrough',
  '/big-walk/yellow-tower-tunnel',
  '/big-walk/blue-tower-train',
  '/big-walk/black-tower',
  '/big-walk/ending-guide',
  '/big-walk/purple-puzzles',
  '/big-walk/puzzles',
  '/big-walk/peg-puzzle',
  '/big-walk/4166-1899-puzzle',
  '/big-walk/how-to-get-shiny',
  '/big-walk/achievements',

  '/fields-of-mistria',
  '/fields-of-mistria/achievements-guide',
  '/fields-of-mistria/bell-tower-guide',
  '/fields-of-mistria/marriage-guide',
  '/fields-of-mistria/how-to-unlock-mines',
  '/fields-of-mistria/saturday-market-plaza',
  '/fields-of-mistria/water-seal-guide',
  '/fields-of-mistria/how-to-unlock-deep-woods',

  '/iron-nest',
  '/iron-nest/how-to-triangulate',
  '/iron-nest/fire-and-light-walkthrough',
  '/iron-nest/liberation-walkthrough',
  '/iron-nest/counter-battery-mission',
  '/iron-nest/iron-road-walkthrough',
  '/iron-nest/siege-of-cartagena-walkthrough',
  '/iron-nest/the-gorge-walkthrough',
  '/iron-nest/rock-of-gibraltar-walkthrough',
  '/iron-nest/dead-reckoning-walkthrough',
  '/iron-nest/fire-on-call-walkthrough',
  '/iron-nest/high-tide-walkthrough',
  '/iron-nest/blind-fire-walkthrough',
  '/iron-nest/phantom-battery-walkthrough',
  '/iron-nest/final-harvest-walkthrough',
  '/iron-nest/white-shells-endings',

  '/sovereign-tower',
  '/sovereign-tower/act-1-best-route',
  '/sovereign-tower/act-2-walkthrough',
  '/sovereign-tower/demon-power',
  '/sovereign-tower/gwendan-questline',
  '/sovereign-tower/groveshire-wolf',
  '/sovereign-tower/south-bay-lamp',
  '/sovereign-tower/king-slayer',
  '/sovereign-tower/golden-key',

  '/pax-autocratica',
  '/pax-autocratica/elysia-walkthrough',
  '/pax-autocratica/capture-enemies-prisoners',
  '/pax-autocratica/work-schedule',
  '/pax-autocratica/core-fragments',
  '/pax-autocratica/mec-kong-boss-guide',

  '/doloc-town',
  '/doloc-town/walkthrough',
  '/doloc-town/environmental-modifier',
  '/doloc-town/money-guide',
  '/doloc-town/best-crops',
  '/doloc-town/acid-rain',
  '/doloc-town/farming-automation',
  '/doloc-town/crop-genetics',
  '/doloc-town/fishing-guide',
  '/doloc-town/fish-breeding',
  '/doloc-town/animals',
  '/doloc-town/achievements',

  '/war-in-the-north-legacy-edition',
  '/war-in-the-north-legacy-edition/walkthrough',
  '/war-in-the-north-legacy-edition/legacy-edition-changes',
  '/war-in-the-north-legacy-edition/best-character-builds',
  '/war-in-the-north-legacy-edition/weapons-mithril-upgrades',
  '/war-in-the-north-legacy-edition/secrets',
  '/war-in-the-north-legacy-edition/side-quests',
  '/war-in-the-north-legacy-edition/lidless-eye-scrolls',
  '/war-in-the-north-legacy-edition/achievements',
  '/war-in-the-north-legacy-edition/co-op-crossplay-troubleshooting',

  '/servant-of-the-lake',
  '/servant-of-the-lake/walkthrough',
  '/servant-of-the-lake/puzzle-solutions',
  '/servant-of-the-lake/waking-up-aldous',
  '/servant-of-the-lake/coffee-puzzle',
  '/servant-of-the-lake/laundry-puzzle',
  '/servant-of-the-lake/bathroom-puzzle',
  '/servant-of-the-lake/alchemy-puzzle',
  '/servant-of-the-lake/achievements',
  '/servant-of-the-lake/secret-ending',
  
] as const;

type SitemapPath = (typeof paths)[number];

// Add a date only after a page receives a meaningful content update.
// Do not use new Date() here: that would mark every deployment as a page update.
const lastModifiedByPath: Partial<Record<SitemapPath, string>> = {
  '/servant-of-the-lake': '2026-08-14',
  '/servant-of-the-lake/walkthrough': '2026-08-14',
  '/servant-of-the-lake/puzzle-solutions': '2026-08-14',
  '/servant-of-the-lake/waking-up-aldous': '2026-08-14',
  '/servant-of-the-lake/coffee-puzzle': '2026-08-14',
  '/servant-of-the-lake/laundry-puzzle': '2026-08-14',
  '/servant-of-the-lake/bathroom-puzzle': '2026-08-14',
  '/servant-of-the-lake/alchemy-puzzle': '2026-08-14',
  '/servant-of-the-lake/achievements': '2026-08-14',
  '/servant-of-the-lake/secret-ending': '2026-08-14',
  
  '/war-in-the-north-legacy-edition': '2026-08-13',
  '/war-in-the-north-legacy-edition/walkthrough': '2026-08-13',
  '/war-in-the-north-legacy-edition/legacy-edition-changes': '2026-08-13',
  '/war-in-the-north-legacy-edition/best-character-builds': '2026-08-13',
  '/war-in-the-north-legacy-edition/weapons-mithril-upgrades': '2026-08-13',
  '/war-in-the-north-legacy-edition/secrets': '2026-08-13',
  '/war-in-the-north-legacy-edition/side-quests': '2026-08-13',
  '/war-in-the-north-legacy-edition/lidless-eye-scrolls': '2026-08-13',
  '/war-in-the-north-legacy-edition/achievements': '2026-08-13',
  '/war-in-the-north-legacy-edition/co-op-crossplay-troubleshooting':
    '2026-08-13',
    
  '/doloc-town': '2026-08-12',
  '/doloc-town/walkthrough': '2026-08-12',
  '/doloc-town/environmental-modifier': '2026-08-12',
  '/doloc-town/money-guide': '2026-08-12',
  '/doloc-town/best-crops': '2026-08-12',
  '/doloc-town/acid-rain': '2026-08-12',
  '/doloc-town/farming-automation': '2026-08-12',
  '/doloc-town/crop-genetics': '2026-08-12',
  '/doloc-town/fishing-guide': '2026-08-12',
  '/doloc-town/fish-breeding': '2026-08-12',
  '/doloc-town/animals': '2026-08-12',
  '/doloc-town/achievements': '2026-08-12',

  '/pax-autocratica': '2026-08-11',
  '/pax-autocratica/elysia-walkthrough': '2026-08-11',
  '/pax-autocratica/capture-enemies-prisoners': '2026-08-11',
  '/pax-autocratica/work-schedule': '2026-08-11',
  '/pax-autocratica/core-fragments': '2026-08-11',
  '/pax-autocratica/mec-kong-boss-guide': '2026-08-11',
  
  '/waterpark-simulator': '2026-08-10',
  '/waterpark-simulator/make-money': '2026-08-10',
  '/waterpark-simulator/staff-guide': '2026-08-10',
  '/waterpark-simulator/museum-guide': '2026-08-10',
  '/waterpark-simulator/5-star-diamond-prestige-guide': '2026-08-10',
  '/waterpark-simulator/mafia-guide': '2026-08-10',

  '/waterpark-simulator/achievements-guide': '2026-08-10',

  '/sovereign-tower/act-1-best-route': '2026-08-09',
  '/sovereign-tower/act-2-walkthrough': '2026-08-09',
  '/sovereign-tower/demon-power': '2026-08-09',
  '/sovereign-tower/gwendan-questline': '2026-08-09',
  '/sovereign-tower/groveshire-wolf': '2026-08-09',
  '/sovereign-tower/south-bay-lamp': '2026-08-09',
  '/sovereign-tower/king-slayer': '2026-08-09',
  '/sovereign-tower/golden-key': '2026-08-09',

  '/iron-nest': '2026-08-08',
  '/iron-nest/fire-and-light-walkthrough': '2026-08-07',
  '/iron-nest/liberation-walkthrough': '2026-08-07',
  '/iron-nest/counter-battery-mission': '2026-08-07',
  '/iron-nest/iron-road-walkthrough': '2026-08-07',
  '/iron-nest/siege-of-cartagena-walkthrough': '2026-08-07',
  '/iron-nest/the-gorge-walkthrough': '2026-08-07',

  '/iron-nest/how-to-triangulate': '2026-08-08',
  '/iron-nest/rock-of-gibraltar-walkthrough': '2026-08-08',
  '/iron-nest/dead-reckoning-walkthrough': '2026-08-08',
  '/iron-nest/fire-on-call-walkthrough': '2026-08-08',
  '/iron-nest/high-tide-walkthrough': '2026-08-08',
  '/iron-nest/blind-fire-walkthrough': '2026-08-08',
  '/iron-nest/phantom-battery-walkthrough': '2026-08-08',
  '/iron-nest/final-harvest-walkthrough': '2026-08-08',
  '/iron-nest/white-shells-endings': '2026-08-08',

  '/fields-of-mistria': '2026-08-06',
  '/fields-of-mistria/achievements-guide': '2026-08-06',
  '/fields-of-mistria/bell-tower-guide': '2026-08-06',
  '/fields-of-mistria/marriage-guide': '2026-08-06',
  '/fields-of-mistria/how-to-unlock-mines': '2026-08-06',
  '/fields-of-mistria/saturday-market-plaza': '2026-08-06',
  '/fields-of-mistria/water-seal-guide': '2026-08-06',
  '/fields-of-mistria/how-to-unlock-deep-woods': '2026-08-06',

  '/big-walk': '2026-08-10',

  '/big-walk/beginner-guide': '2026-08-05',
  '/big-walk/tutorial-walkthrough': '2026-08-05',
  '/big-walk/how-to-unlock-map': '2026-08-05',
  '/big-walk/green-tower-walkthrough': '2026-08-05',
  '/big-walk/yellow-tower-tunnel': '2026-08-05',
  '/big-walk/blue-tower-train': '2026-08-06',
  
  '/big-walk/black-tower': '2026-08-10',
  '/big-walk/ending-guide': '2026-08-10',
  '/big-walk/purple-puzzles': '2026-08-10',
  
  '/big-walk/puzzles': '2026-08-10',
  '/big-walk/peg-puzzle': '2026-08-10',
  '/big-walk/4166-1899-puzzle': '2026-08-10',
  '/big-walk/how-to-get-shiny': '2026-08-10',
  '/big-walk/achievements': '2026-08-10',

  '/what-game-should-i-play': '2026-08-04',
  '/scrap-mechanic/first-grow-lab-walkthrough': '2026-08-04',
  '/grim-dawn-fangs-of-asterkarn/ritual-of-cleansing-walkthrough':
    '2026-08-04',
  '/grim-dawn-fangs-of-asterkarn/soul-echoes-awaken-epic-items':
    '2026-08-04',
  '/dragonsword-awakening/best-team-comps': '2026-08-04',
  '/tears-of-metal': '2026-08-04',
  '/tears-of-metal/characters-companion-unlocks': '2026-08-04',

};

export default function sitemap(): MetadataRoute.Sitemap {
  return Array.from(new Set<SitemapPath>(paths)).map((path) => {
    const lastModified = lastModifiedByPath[path];

    return {
      url: `${baseUrl}${path}`,
      ...(lastModified ? { lastModified } : {}),
    };
  });
}